[project]
name = "shaders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
"moderngl",
  "pyglet",
  "pyvista",
  "cvzone",
  "mediapipe",
]
